### PR TITLE
chore: add notifications to request map

### PR DESCRIPTION
**Pull request by im-adithya**
get-info shows undefined in between because of this

### CODE REVIEW

**Comment by rolznz** [comment]
@im-adithya this is not correct, it's not a request.

**Comment by im-adithya** [comment]
Then should I filter out while returning request_methods in get info call? How will the dev know that it supports notifications?

**Comment by rolznz** [comment]
> get-info shows undefined in between because of this

@im-adithya can you show an example?

> Then should I filter out while returning request_methods in get info call?

Why do you need to filter something out?

> How will the dev know that it supports notifications?

can we add the supported notification types to `Nip47GetInfoResponse`?

**Comment by rolznz** [comment]
@im-adithya I think I missed this in the spec PR. It's published as a tag in the replaceable info event but not in the response of the `get_info` NIP-47 request method. Thanks for raising this - I think we need to update that as well.

**Pull request closed without merging**
