### PR TITLE
doc: make loadNWCUrl example more clear

### PR DESCRIPTION
**Pull request by rolznz**
Two users so far have asked about this.

### CODE REVIEW

**Comment by pavanjoshi914** [comment]
I kinda always ignore notes thinking that should be optional :smiley:  if something is mandatory information I prefer to mention it directly or in a separate section so that the user can have its attention on it! but really depends

like here we are asking user to create nwc url, and then again a second link and then again implement function by yourself

**Comment by rolznz** [comment]
@pavanjoshi914 I bolded the note, but it is not perfect. Do you have a better idea?

**Comment by bumi** [comment]
+1 in docs we can expect people to read docs. If a developer ignores the docs and does not read it it is their fault.
we can not build their apps, they have to do semething.

we can link to the examples  - and also add some more examples.

**Comment by rolznz** [comment]
Ok, I will close this for now. We can provide support for devs who get stuck.

**Pull request closed without merging**
